#!/usr/bin/python3
import itertools
import os

# Generate all combinations of parameter values using itertools.product
output_dir = "result"
num_threads_range = [1, 2, 4, 8]
write_fraction_range = [0.01, 0.2, 0.4, 0.6, 0.8, 0.99]
read_time_range = [1000, 10000, 100000]
write_time_range = [1000, 10000, 100000]
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
param_combinations = list(itertools.product(
    num_threads_range, write_fraction_range, write_time_range, read_time_range))

# run experiment
for num_threads, write_fraction, write_time, read_time in param_combinations:
    if read_time > write_time:
        continue
    cmd = f'./lock-test -t {num_threads} -w {write_fraction} -W {write_time} -r {read_time} -o {output_dir}'
    os.system(cmd)
