#!/usr/bin/python3
import argparse
import itertools
import os
import numpy as np

# Generate all combinations of parameter values using itertools.product
output_dir = "result"
num_threads_range = [1, 2, 4, 8, 16]
write_fraction_range = [0.1, 0.25, 0.5, 0.75, 0.99]
write_time_range = [1000, 10000, 100000]
read_time_range = [1000, 10000, 100000]
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
param_combinations = list(itertools.product(num_threads_range, write_fraction_range, write_time_range, read_time_range))


# run experiment
# for num_threads, write_fraction, write_time, read_time in param_combinations:    
#     cmd = f'./lock-test -t {num_threads} -w {write_fraction} -W {write_time} -r {read_time} -o {output_dir} > /dev/null &2>1'
#     os.system(cmd)


def parse_filename(filename: str):
    

# figure
files = os.listdir(output_dir)
for file in files:
    print(file)